// Code generated by goctl. DO NOT EDIT.
// Source: simple.proto

package server

import (
	"context"

	"simple/internal/logic/exampleservice"
	"simple/internal/svc"
	"simple/pb"
)

type ExampleServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedExampleServiceServer
}

func NewExampleServiceServer(svcCtx *svc.ServiceContext) *ExampleServiceServer {
	return &ExampleServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ExampleServiceServer) Example(ctx context.Context, in *pb.NoContentReq) (*pb.NoContentResp, error) {
	l := exampleservicelogic.NewExampleLogic(ctx, s.svcCtx)
	return l.Example(in)
}
