// Code generated by goctl. DO NOT EDIT.
// Source: simple.proto

package exampleservice

import (
	"context"

	"simple/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	NoContentReq  = pb.NoContentReq
	NoContentResp = pb.NoContentResp

	ExampleService interface {
		Example(ctx context.Context, in *NoContentReq, opts ...grpc.CallOption) (*NoContentResp, error)
	}

	defaultExampleService struct {
		cli zrpc.Client
	}
)

func NewExampleService(cli zrpc.Client) ExampleService {
	return &defaultExampleService{
		cli: cli,
	}
}

func (m *defaultExampleService) Example(ctx context.Context, in *NoContentReq, opts ...grpc.CallOption) (*NoContentResp, error) {
	client := pb.NewExampleServiceClient(m.cli.Conn())
	return client.Example(ctx, in, opts...)
}
